User.create(name: 'James T. Kirk')
User.create(name: 'Spock')
User.create(name: 'Leonard McCoy')
User.create(name: 'Montgomery Scott')
User.create(name: 'Nyota Uhura')
User.create(name: 'Pavel Chekov')
User.create(name: 'Hikaru Sulu')